name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Vérifier les dépendances
        run: |
          pip check

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - name: Contrôler le Dockerfile
        run: |
          hadolint Dockerfile

      - name: Construire l'image Docker
        run: |
          docker build -t mon-app:latest -f Dockerfile .

      - name: Scanner l'image Docker avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mon-app:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
